# Generated by Django 2.1.1 on 2018-10-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='设备名称')),
                ('sn', models.CharField(max_length=50, verbose_name='设备序列号')),
                ('ip', models.CharField(max_length=50, verbose_name='设备IP')),
                ('netmask', models.CharField(max_length=50, verbose_name='子网掩码')),
                ('netgate', models.CharField(max_length=50, verbose_name='网关')),
                ('mac', models.CharField(max_length=50, verbose_name='MAC')),
            ],
            options={
                'verbose_name': '设备信息表',
                'verbose_name_plural': '设备信息表',
            },
        ),
    ]
