# Generated by Django 2.1.1 on 2018-10-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceManage', '0002_device_ver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': '设备', 'verbose_name_plural': '设备'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
        migrations.AlterField(
            model_name='device',
            name='sn',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='设备序列号'),
        ),
    ]
