# Generated by Django 2.2 on 2019-06-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='菜单图标'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(max_length=50, verbose_name='菜单链接地址'),
        ),
    ]
