# Generated by Django 2.2 on 2019-06-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='设备名称')),
                ('sn', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='设备序列号')),
                ('ip', models.CharField(max_length=50, verbose_name='设备IP')),
                ('netmask', models.CharField(max_length=50, verbose_name='子网掩码')),
                ('netgate', models.CharField(max_length=50, verbose_name='网关')),
                ('mac', models.CharField(max_length=50, verbose_name='MAC')),
                ('ver', models.CharField(default='', max_length=50, verbose_name='硬件版本')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
    ]
